config/routes.rb
Mondai::Application.routes.draw do
  get "home/show"
  match "/public" => "home#public", :as => 'public'

  match 'questions/page/:page' => "questions#show_more"
  match '/search/' => 'home#search', :as => "search"
  resources :questions do
    resources :answers do
       put :vote_up
       put :vote_down
    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  match 'u/:name/:id' => 'users#show', :as => "show_user"
  match '/:name/:id' => 'questions#show', :as => "show_question"
  match '/topic/:name/:id' => 'topics#show', :as => 'show_topic'
  get 'answers/edit/:id' => 'answers#edit', :as => 'answer_edit'
  put 'answers/edit/:id' => 'answers#update', :as => 'answer_edit'
  
  match '/tos', :to => 'pages#tos'
  match '/about', :to => 'pages#about'
  

  root :to => "home#index"

end

app/models/question.rb
class Question < ActiveRecord::Base

  attr_accessible :content, :description, :name, :topic_names
  attr_accessor :topic_names
  belongs_to :user
  has_many :enrollments
  has_many :topics, :through => :enrollments
  has_many :answers, :dependent => :destroy
  validates :content, :presence => true
  
  #generates a method topic_names= that sets the value of the instance variable @topic_names
  #attr_writer :topic_names
  after_save :assign_topics
  default_scope :order => 'questions.created_at DESC'
  
  def normalized_name
    self.content.gsub(' ', '-').gsub('.', '').gsub(/[^a-zA-Z0-9\_\-\.]/, '')
  end
  
  def topic_names
    #this allows to see the topics when we click edit
    @topic_names || topics.map(&:name).join(', ')
  end
  
  
  def assign_topics
    if @topic_names
      #assign the correct associations in our model
      #allow for comma separated
      self.topics = @topic_names.split(/,\s*/).map do |name|
        name = name.gsub('.', '').gsub(/[^a-zA-Z0-9\s\_\-\.]/, '').strip.downcase
        Topic.find_or_create_by_name(name)
      end
    end
  end
  
  def self.search(search)
    if !search.empty?
      where('lower(content) LIKE ?', "%#{search.downcase}%")
    end
  end
  
  #Return Question that is belongs to the followed user to show in the current user profile page
  scope :from_users_followed_by, lambda { |user| user_followed_by(user) }
  scope :from_questions_followed_by, lambda { |question| question_followed_by(user) }
  scope :from_topic_followed_by, lambda { |topic| topic_followed_by(user)}
  
  private
    #Return an SQL condition statement for users followed by current user
    def self.user_followed_by(user)
      user_following_ids = %(SELECT u_followed_id FROM u_relationship WHERE u_follower_id = :user_id)
      where("user_id IN (#{user_following_ids}) OR user_id = :user_id", {:user_id => user})
    end
    
    def self.question_followed_by(user)
      q_following_ids = %(SELECT q_followed_id FROM q_relationship WHERE q_follower_id = :user_id)
      where("user_id IN (#{q_following_ids}) OR user_id = :user_id", {:user_id => user})
    end
    
    def self.topic_followed_by(user)
      t_following_name = %(SELECT t_followed FROM t_relationship WHERE t_follower_id = :user_id)
      where("user_id IN (#{t_following_ids}) OR user_id = :user_id", {:user_id => user})
    end
    

end


# == Schema Information
#
# Table name: questions
#
#  id          :integer         not null, primary key
#  content     :text
#  description :text
#  user_id     :integer
#  has_answer  :boolean
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  #before_filter :authenticate, :only => [:create, :destroy] 
  #before_filter :authorized_user, :only => :destroy 
  
  # Need to discuss before us to implement these 2 funcs 
  before_filter :authenticate_user!, :only => :new
  before_filter :store_location
   
  def new
    @question = Question.new
  end
  
  def create
    @question = current_user.questions.create(params[:question])
    if @question.save
      redirect_to show_question_path(@question.normalized_name, @question)
    else
      render 'new'
    end
  end
  
  def edit
    @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to show_question_path(@question.normalized_name, @question)}
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors,
                      :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(root_path) }
      format.xml  { head :ok }
    end
  end
  
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @question }
    end
  end
  
  def show_more
    @questions = Question.page(params[:page]).per(2)
    render :layout => false
  end
  
  
  
  #Allowing admin to delete question
  private
    def authorized_user
      @question = Question.find(params[:id])
      redirect_to root_path unless current_user?(@question.user)
    end
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
  # keeping the length of question to fit some constant amout of 
  # characters per line
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s)}.join(' ')))
  end
  private
    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
  
end

app/views/questions/_form.html.erb
<div id="five_center">	
	<%= form_for(@question) do |f| %>

	<% if @question.errors.any? %>
	  <div id="errorExplanation">
	    <h2><%= pluralize(@question.errors.count, "error") %> prohibited this post from being saved:</h2>
	    <ul>
	    <% @question.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>
		<%= f.label "Question:" %><br />
		<%= f.text_field :content, :size => "48px" %><br />
		<%= f.label "Description (Optional):" %><br />
		<%= f.text_area :description, :size => "50x10", :placeholder => 'Provide more details about your question' %><br />
		<%= f.label "Question Topics:" %><br />
		<%= f.text_field :topic_names, :size => "48px", :placeholder => 'Binghamton, Downtown, Math, Teachers, etc',:id => :topics %><br />
		<%= add_button_tag "Post Question", :id=>"qb" %><br />
	<% end %>
</div>
<%= stylesheet_link_tag 'jqui.custom.css', :media => 'screen' %>
<%= javascript_include_tag  "jqui.min.js" %>

app/views/questions/_questions.html.erb
<% cache(question) do %> 
	<div class="question">
			<div class="question_image">
				<%= image_tag question.user.picture %>
			</div>
			<div class="question_content">
			<%= link_to question.content, show_question_path(question.normalized_name, question) %><br />
	  <% if question.description.empty? %>
	    <br />
	  <% else %>
	    <%= question.description %>
	  <% end %>
	  <p class="asked">
	  	Asked by: <%= question.user.name %> | <%= question.answers.length %> responses
	  </p>
	</div>
	</div><div class="clear"></div>
<% end %>

app/views/questions/edit.html.erb
<script type="text/javascript" charset="utf-8">
	
 $(document).ready(function() {
   // put all your jQuery goodness in here.
	$("#qb").html("Edit Question");
 });

</script>
<%= render 'form' %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<% title @question.content %>
<% description @question.description %>
<% unless current_user %>
	<div class="container">
<% end %>
	<div id="question_container">	
		<div id="topics">
			<h2>Topics:</h2>
			<div class="topic_container">
				<ul class ="question_topics">
					<% for topic in @question.topics %>
						<li>
							<%=h link_to topic.name.titleize, show_topic_path(topic.name, topic) %>
						</li>
					<% end %>
				</ul>
			</div>
		</div><div class="clear"></div>
	
		<div id="question">
			<h1>
			  <%=h @question.content %>
			</h1>
			<p id="q_description">
			  <%=h @question.description %>
			</p>
				<% if !current_user.nil? && current_user.id ==  @question.user.id %>
				<p>
        <%= link_to 'Edit', edit_question_path(@question), :class => "edit"%>
				</p>
				<% end %>
				<div class="socialshare">
					<ul id="socialshare">
						<li class="sharetext">
							<b>Share With Friends</b>
						</li>
						<li>
							<div id="fb-root"></div>
							<fb:like href="" send="true" layout="button_count" width="100" show_faces="false" font="lucida grande"></fb:like>
						</li>
						<li class="gplus">
							<g:plusone size="medium"></g:plusone>	
						</li>
						<li class="twitter">
							<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a>
						</li>
					</ul>
				</div>
		</div><div class="clear"></div>
	
		<div id="answer">
      <h2>Answers:</h2>
        <span class="tip_up">Click here to vote up</span> 
        <span class="tip_down">Click here to vote down</span><br />
			<div id="answers_container">
					<% @question.answers.each do |answer| %>
						<%= render :partial => answer %>
					<% end %>
        </div>
		</div>
		<div id="answer_box">
			<h4>Your Answer:</h4>
			<%= form_for :answer, :url => question_answers_path(@question), :remote => true do |f| %>
				<%= f.text_area :content, :cols => 80, :rows => 10 %>
				<%= comment_button_tag "Submit Response"%>
			<% end %>
		</div>
		<%# link_to 'Home', root_path %>
		
	</div><!-- #question_container -->
	<div id="toprightbox">
		<p>
			<h3>Question Owner</h3>
		</p>
		<div id="profileimage">
			<%= image_tag @question.user.picture %>
		</div>
		<div id="profileabout">
			<p>
				<%= @question.user.name %>
			</p>
			<p>
				<%= @question.user.description %>
			</p>
    </div><div class="clear"></div>
    <div id="votingabout">
      <h3>Vote for your favorites!</h3>
    <p>
        Support the answers you like by voting for them.
    </p>
  </div>

  </div>
</div>
<div class="clear"></div>

app/views/questions/show_more.html.erb
<% @questions.each do |question| %>
	<div class="question">
		<div class="question_image">
			<%= image_tag question.user.picture %>
		</div>
		<div class="question_content">
			<%= link_to question.content, show_question_path(question.normalized_name, question) %><br />
			<%= question.description %>
		</div>
	</div>
<% end %>
<div id="attach">
</div>