config/routes.rb
Mondai::Application.routes.draw do
  get "home/show"
  match "/public" => "home#public", :as => 'public'

  match 'questions/page/:page' => "questions#show_more"
  match '/search/' => 'home#search', :as => "search"
  resources :questions do
    resources :answers do
       put :vote_up
       put :vote_down
    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  match 'u/:name/:id' => 'users#show', :as => "show_user"
  match '/:name/:id' => 'questions#show', :as => "show_question"
  match '/topic/:name/:id' => 'topics#show', :as => 'show_topic'
  get 'answers/edit/:id' => 'answers#edit', :as => 'answer_edit'
  put 'answers/edit/:id' => 'answers#update', :as => 'answer_edit'
  
  match '/tos', :to => 'pages#tos'
  match '/about', :to => 'pages#about'
  

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :authenticate_user!, :only => :show 
  before_filter :store_location
  
  def index
    if !!current_user
      #show news feed or popular questions
      @questions = Question.page(params[:page]).per(10)
      @topics = Topic.all  
      render :action => 'logged_in_user'
    else
      render :action => 'new_user'
    end
  end

  def public
    @questions = Question.page(params[:page]).per(10)
    @topics = Topic.all  
    render :action => 'logged_in_user'
  end

  def show
    #@questions = Question.all
    redirect_to root_path  
  end
  
  def search
    @questions = Question.search(params[:search]).page(params[:page]).per(10)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_question.html.erb
<% cache(question) do %> 
	<div class="question">
			<div class="question_image">
				<%= image_tag question.user.picture %>
			</div>
			<div class="question_content">
			<%= link_to question.content, show_question_path(question.normalized_name, question) %><br />
	  <% if question.description.empty? %>
	    <br />
	  <% else %>
	    <%= question.description %>
	  <% end %>
	  <p class="asked">
	  	Asked by: <%= question.user.name %> | <%= question.answers.length %> responses
	  </p>
	</div>
	</div><div class="clear"></div>
<% end %>

app/views/home/index.html.erb
<script type="text/javascript" charset="utf-8">
	if(window.opener) {
	    window.opener.location.reload(true);
	    window.close()
	  }
</script>
<div id="centerContainer">
<div id="signin">
	<div class="regular signinsubmit">
	<h3>Log In</h3>
	<%= form_for("user", :url => user_session_path) do |f| %>
	  <div class="singleField">
		<%= f.label :email %>
	    <%= f.email_field :email %></div>
	  <div class="singleField">
		<%= f.label :password %>
	  	<%= f.password_field :password %>
	  </div>
	   <div class="singleField">
		<%= f.label :remember_me %>
		<%= f.check_box :remember_me %> 
	   </div>

	  <p><%= positive_button_submit_tag "Sign in" %> <span id="or"> or</span>
		<%= primary_button_link_to "Sign In With Facebook", user_omniauth_authorize_path(:facebook), :class => "popupp", :"data-width" => 600, :"data-height" => 400 %></p>
	<% end %>
	</div>
</div>
<div id="signup">
	<%= big_primary_button_link_to "Sign Up With Facebook", user_omniauth_authorize_path(:facebook), :class => "popupp", :"data-width" => 600, :"data-height" => 400 %>
	<div class="regular hsubmit">
		<%= form_for("user", :url => user_registration_path) do |f| %>
		  <div class="singleField"><label>Name</label><%= f.text_field :name %></div>
		  <div class="singleField"><label>Email</label><%= f.text_field :email %></div>
		  <div class="singleField"><label>Password</label> <%= f.password_field :password %></div>
		  <div class="singleField submit"><%= big_primary_button_submit_tag 'Sign up' %></div>
		  <div class="clear"></div>
		<% end %>
	</div>
</div>
</div>

<%= link_to "New Question" , new_question_path %>
<%= link_to "View Your Questions", home_show_path %>

app/views/home/logged_in_user.html.erb
<div id="question_container">	
	<div id="askquestion">
		<%= add_button_link_to "Ask A Question" , new_question_path %>
	</div>
	<h1>Share what you know. Answer new questions.</h1>
	<%= render :partial => "question", :collection => @questions %>
	<!-- <% @questions.each do |question| %>
		<div class="question">
			<div class="question_image">
				<%= image_tag question.user.picture %>
			</div>
			<div class="question_content">
				<%= link_to question.content, show_question_path(question.normalized_name, question) %><br />
        <% if question.description.empty? %>
          <br />
        <% else %>
          <%= question.description %>
        <% end %>
        <p class="asked">
        Asked by: <%= question.user.name %> | <%= question.answers.length %> responses
        </p>
      </div>
	  </div><div class="clear"></div>	
	<% end %> -->
	<div id="attach">
	</div>
</div>
	<div id="toprightbox">
		<h2 id="boxtopics">Top Topics</h2>
		<div class="topic_container">
			<ul class ="all_topics">
				<% @topics.each do |topic|%>
					<li>
						<%= link_to topic.name.titleize, show_topic_path(topic.name, topic) %>
					</li>
				<% end %>
      </ul>
    </div>
    							<div id="fb-root"></div>
							<fb:like href="" send="true" layout="button_count" width="100" show_faces="false" font="lucida grande"></fb:like>
						
					  </br>
							<g:plusone size="medium"></g:plusone>	
              </br>
								<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a>
							</div>	
<div class="clear"></div>
<div id="paginate">
	<%# link_to "Load more", "#", :class => "next" %>
	<%= paginate @questions %>
</div><div class="clear"></div>
<script src="http://connect.facebook.net/en_US/all.js#appId=233421873346550&amp;xfbml=1"></script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

app/views/home/new_user.html.erb
<style type="text/css" media="screen">
	#footer{
		margin-top:0px;
	}
	body {
        overflow: hidden;
	}
</style>
<body>
<div id="bigimage">
</div>
<div id="middleAbout">
	<div id="header">
		<h1>DISCOVER YOUR CAMPUS AND GET THE BEST ANSWERS TO YOUR QUESTIONS</h1>
	</div>
	<div id="footerbottom">
		<div id="footersignin">
			<h2>Sign in to join our beta with your facebook account or Click on public preview to get a sneak peak!</h2>
			<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class=> "ir social" %>
			<a class="small blue awesome" href="http://mondai.me/public">Preview Site &raquo;</a>
			<p>Start To Question Your Campus!</p>
			<small>Want this service for your campus too? Let us know and we'll be in touch!</small>
		</div><!-- #footersignin -->
	</div>
</div><div class="clear"></div>
<div class="clear"></div>
</div>
</body>
<script src="http://connect.facebook.net/en_US/all.js#appId=233421873346550&amp;xfbml=1"></script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

app/views/home/search.html.erb
<br />
<% if @questions.blank? %>
	<p>
		Sorry nothing found yet. We are working on improving search
	</p>
	<% else %>
		<p>
			These are your results.
		</p>
		<% @questions.each do |question| %>
			<div class="question">
				<div class="question_image">
					<%= image_tag question.user.picture %>
				</div>
				<div class="question_content">
					<%= link_to question.content, show_question_path(question.normalized_name, question) %><br />
					<%= question.description %>
				</div>
			</div><div class="clear"></div>	
		<% end %>
<% end %>
<div id="paginate">
	<%# link_to "Load more", "#", :class => "next" %>
	<%= paginate @questions %>
</div><div class="clear"></div>

app/views/home/show.html.erb
<% @questions.each do |question| %>
	<div class="question">
		<%= question.content %>
	</div>
	
<% end %>