config/routes.rb
Mondai::Application.routes.draw do
  get "home/show"
  match "/public" => "home#public", :as => 'public'

  match 'questions/page/:page' => "questions#show_more"
  match '/search/' => 'home#search', :as => "search"
  resources :questions do
    resources :answers do
       put :vote_up
       put :vote_down
    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  match 'u/:name/:id' => 'users#show', :as => "show_user"
  match '/:name/:id' => 'questions#show', :as => "show_question"
  match '/topic/:name/:id' => 'topics#show', :as => 'show_topic'
  get 'answers/edit/:id' => 'answers#edit', :as => 'answer_edit'
  put 'answers/edit/:id' => 'answers#update', :as => 'answer_edit'
  
  match '/tos', :to => 'pages#tos'
  match '/about', :to => 'pages#about'
  

  root :to => "home#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :user_id, :count
  belongs_to :user
  belongs_to :question
  has_many :votes
  
  def total_sum
    self.votes.sum(:value)
  end

  validates :content, :presence => true
  #default_scope :include => :votes
  default_scope :order => 'count DESC'
end


# == Schema Information
#
# Table name: answers
#
#  id          :integer         not null, primary key
#  content     :text
#  user_id     :integer
#  question_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  #before_filter :authenticate, :only => [:create, :destroy] 
  #before_filter :authorized_user, :only => :destroy 
  
  # Need to discuss before us to implement these 2 funcs
  before_filter :authenticate_user!

  def new
    @answer = Answer.new  
  end
  
  
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(params[:answer])
    @answer.user = current_user
    respond_to do |format|
      if @answer.save
        format.html { redirect_to show_question_path(@answer.question.normalized_name,@answer.question) }
        format.js
        send_mail(@question)
      else
        render 'new'
      end
    end
  end
  
  def edit
    @answer = Answer.find(params[:id])
  end
  
  def update
    @answer = Answer.find(params[:id])
    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to(session[:return_to],
                      :notice => 'Answer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @answer.errors,
                      :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to(show_question_path(Question.find(params[:question_id]).normalized_name, params[:question_id],)) }
      format.js
    end
  end
  
  def show
    @answer = Answer.find(params[:id])
    respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @post }
    end
  end 
  
  def vote_up
    @answer = Answer.find(params[:answer_id])
    if vote(:for, current_user, @answer)
      @answer.update_attributes(:count => (@answer.count+=1)) 
      #@answer.save
      flash[:notice] = "Thank you for voting"
      respond_to do |format|
        format.html { redirect_to show_question_path(@answer.question.normalized_name,@answer.question) }
        format.js
      end
    else
      flash[:notice] = "Your vote has already been registered"
      respond_to do |format|
        format.html { redirect_to show_question_path(@answer.question.normalized_name,@answer.question) }
        format.js
      end
    end
  end
  
  def vote_down
    @answer = Answer.find(params[:answer_id])
    if vote(:against, current_user, @answer)
      flash[:notice] = "Thank you for voting"
      @answer.update_attributes(:count => (@answer.count-=1)) 
      respond_to do |format|
        format.html { redirect_to show_question_path(@answer.question.normalized_name,@answer.question) }
        format.js
      end
    else
      flash[:notice] = "Your vote has already been registered"
      respond_to do |format|
        format.html { redirect_to show_question_path(@answer.question.normalized_name,@answer.question) }
        format.js
      end
    end
  end
   
  #Allowing admin to delete answer
  private
    def vote(value, user, answer)
      new_vote = false
      #find vote for this instance by the given user OR create a new one
      vote = answer.votes.where(:user_id => current_user.id).first || answer.votes.create(:user_id => current_user.id)

      if value == :for
        vote_value = 1
      elsif value == :against
        vote_value = -1
      end

      if vote.value != vote_value
        vote.value = vote_value
        vote.save
        new_vote = true
      end
      
      return new_vote
    end
    
    def authorized_user
      @answer = Answer.find(params[:id])
      redirect_to root_path unless current_user?(@answer.user)
    end

    def send_mail(question)
        CommentMailer.comment_notify(question).deliver      
    end
end

app/helpers/answer_helper.rb
module AnswerHelper
  
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s)}.join(' ')))
  end
  
  private
    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    
    end
  
end

app/views/answers/_answer.html.erb
<div class="single_answer_container" id="answer_<%= answer.id %>">
	<div class="user">
		<%= image_tag answer.user.picture, :size => "25x25" %>
	</div>
	<p class="user_name user_path">
		<%= link_to answer.user.name, show_user_path(answer.user.name, answer.user.id) %>
	</p>
	<div class="single_answer">
		<%= raw sanitize(auto_link(simple_format(answer.content, :class=> 'psafeanswer'), :tags => %w(strong em b i hr br ul ol li blockquote p) )) %>
		<% if !current_user.nil? && answer.user.id == current_user.id %>
			<p class="change_response">
      <%= link_to "Edit", answer_edit_path(answer), :class => "edit"%>
			<%= link_to "Delete", question_answer_path(@question,answer),:class => "delete",
				 :confirm => 'Are you sure?', :method => :delete, :remote => true %>
			</p>
		<% end %>
	</div>
	<div class="vote_container">	
		<p class="vote_up">
      <%= link_to image_tag("vote_up2.png"), question_answer_vote_up_path(@question, answer),:class => "tip_trigger", :method => :put, :remote => true %>
    </p>

		<p class="vote_count" id="vote_id_<%= answer.id %>">
			<%= answer.total_sum %>
    </p>

		<p class="vote_down">
    <%= link_to image_tag("vote_down2.png"), question_answer_vote_down_path(@question, answer), :class=>"tip_trigger",:method => :put, :remote => true %>
		</p>
	</div>
	<div class="clear"></div>
</div><!-- .single_answer_container -->

app/views/answers/create.js.erb
$("#answers_container").append("<%= escape_javascript(render(@answer)) %>");
$("#answer_box form")[0].reset();
$("#answer_<%= @answer.id %>").effect("highlight", {}, 3000);
retrigger();

app/views/answers/destroy.js.erb
$('#answer_<%= @answer.id %>').fadeOut();

app/views/answers/edit.html.erb
<div id="five_center">	
	<%= form_for(@answer, :url => answer_edit_path) do |f| %>

	<% if @answer.errors.any? %>
	  <div id="errorExplanation">
	    <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this post from being saved:</h2>
	    <ul>
	    <% @answer.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>
		<%= f.label "Answer" %><br />
		<%= f.text_area :content, :size => "55x10" %><br />
		<%= add_button_tag "Save Answer" %><br />
	<% end %>
</div>

app/views/answers/vote_down.js.erb
$("#vote_id_<%= @answer.id %>").html("<%= @answer.total_sum %>");
$("#flashes").html('<div class="flash notice" id="flash_notice"><%= escape_javascript(flash.delete(:notice)) %></div>');
positionFlash();
$('#flash_notice').delay(3000).fadeOut('slow');
//$("#answer_<%= @answer.id %>").effect("highlight", {}, 3000);

app/views/answers/vote_up.js.erb
$("#vote_id_<%= @answer.id %>").html("<%= @answer.total_sum %>");
$("#flashes").html('<div class="flash notice" id="flash_notice"><%= escape_javascript(flash.delete(:notice)) %></div>');
positionFlash();
$('#flash_notice').delay(3000).fadeOut('slow');
//$("#answer_<%= @answer.id %>").effect("highlight", {}, 3000);