config/routes.rb
Mondai::Application.routes.draw do
  get "home/show"
  match "/public" => "home#public", :as => 'public'

  match 'questions/page/:page' => "questions#show_more"
  match '/search/' => 'home#search', :as => "search"
  resources :questions do
    resources :answers do
       put :vote_up
       put :vote_down
    end
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }
  match 'u/:name/:id' => 'users#show', :as => "show_user"
  match '/:name/:id' => 'questions#show', :as => "show_question"
  match '/topic/:name/:id' => 'topics#show', :as => 'show_topic'
  get 'answers/edit/:id' => 'answers#edit', :as => 'answer_edit'
  put 'answers/edit/:id' => 'answers#update', :as => 'answer_edit'
  
  match '/tos', :to => 'pages#tos'
  match '/about', :to => 'pages#about'
  

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title).blank? ? "Question Your Campus | Binghamton University" : yield(:title) %> - Mondai.me</title>
  <link rel="shortcut icon" href="/logo.png" />
	<meta name="Description" content="The best place to ask questions about your campus. We're here to help connect you and your campus together."> 
  <meta name="Keywords" content="Binghamton University, Mondai, Mondai.me, Mondai me, Binghamton, Questions, Answers, QA">
  <meta name="google-site-verification" content="rBw2Nvw-zfzRv0u3_IDikaogP0YpszRacKOtqeJmMlc" />
	<meta property="og:title" content="<%= yield(:title).blank? ? 'Question Your Campus | Binghamton University' : yield(:title) %> - Mondai.me"/>
	<meta property="og:type" content="article"/>
	<meta property="og:image" content="http://mondai.me/images/logo150.png"/>
	<meta property="og:url" content="<%= request.url %>"/>
	<meta property="og:site_name" content="Mondai.me"/>
	<meta property="fb:admins" content="559755285"/>
	<meta property="og:description"
	          content="<%= yield(:title).blank? ? 'Mondai is the best way to discover your campus and get your questions answered by the people around you.' : yield(:title) %>"/>
  <%= css3buttons_stylesheets %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jqui.min.js" %>
  <%= csrf_meta_tag %>
	<meta name="google-site-verification" content="EZcXSlkekpeFa9viMrQUyszmS0j7ZuYp2ocJ6FMRkEk" />
</head>
<body>
<div id="topbar">
	<div class="topnav_container">
		<h1 class="logo0"><%= link_to "Mondai.me", root_path , :class => "home logo ir" %></h1>
		<% if current_user %>
			<ul id="topnav">
				<li>
					<form action="<%= search_path %>" method="get" >
				    <%= text_field_tag :search, params[:search], :class => 'searchBox', :placeholder => "Search for a Question" %>
				</li>
				<li>
					<%= search_button_tag "Search", :name => nil, :class=> 'search' %>
				  </form>
				</li>
			</ul>
			<ul id="toplinks">
				<%= button_group do %>
					<%= button_link_to "Profile", show_user_path(current_user.normalized_name, current_user) %>
					<%= button_link_to "Log Out", destroy_user_session_path %>		
				<% end %>
			</ul>
		<% else %>
				<ul id="topnavmore">
					<li id="learnmore"><%= link_to "Learn More", about_path %></li>
				</ul>
				
				<div class="socialsharenav">
					<ul id="socialshare">
						<li>
							<div id="fb-root"></div>
							<fb:like href="" send="true" layout="button_count" width="100" show_faces="false" font="lucida grande"></fb:like>
						</li>
						<li class="gplus">
							<g:plusone size="medium"></g:plusone>	
						</li>
						<li class="twitter">
							<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a>
						</li>
					</ul>
				</div>
				<ul id="toplinks">
					<li>
						<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class=> "ir social" %>
					</li>
					<li id="return">
						Returning User?
					</li>
				</ul>
		<% end %>
	</div>
</div>
<div class="clear"></div>
<% if current_user || current_page?('/public') || (request.url.include? "topic") || (request.url.include? "/u/") %>
  	<div class="container">
<% else %>
		<div class="mainpage">
<% end %>
	<div id="flashes">

	  <% if flash[:notice] %>
	    <p id="flash_notice" class="messages notice"><%= flash[:notice] %></p>
	    <%= javascript_tag "$('#flash_notice').delay(3000).fadeOut('slow');" %>
	  <% end %>

	  <% if flash[:error] || flash[:errors] %>
	    <p id="flash_errors" class="messages errors alert"><%= flash[:error] || flash[:errors] %></p>
	    <%= javascript_tag "$('#flash_errors').delay(3000).fadeOut('slow');" %>
	  <% end %>

	  <% flash[:error] = flash[:errors] = flash[:notice] = nil %>
	</div>
    <%= yield %>
 </div>
<div class="clear"></div>

</body>
<% if current_user %>
<div id="footer2"><div class="clear"></div>
<% else %>
<div id="footer"><div class="clear"></div>
<% end %>
	<nav class="round">
		<ul>
			<li><%= link_to "About Mondai", about_path %></li>
			<li><%= link_to "Terms and Privacy", tos_path %></li>
			<li><a href="http://www2.binghamton.edu/" target="_blank">Binghamton University</a></li>
			<li><a href="http://twitter.com/#!/Mondai_Me" target="_blank">Follow us on Twitter</a></li>
			<li><a href="http://www.facebook.com/pages/Mondai/124140844342288" target="_blank">Mondai on Facebook</a></li>
		</ul>
	</nav>
</div>
</html>
<!--
<script type="text/javascript">
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/Z2rJokeTkxwzRjPim8sedA.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();
</script>
-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17557178-6']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script src="http://connect.facebook.net/en_US/all.js#appId=233421873346550&amp;xfbml=1"></script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>